# Generated by Django 3.2.8 on 2021-10-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='user',
            name='social',
        ),
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
